default: &default
  adapter: postgresql
  port: 5432
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: 

test:
  <<: *default
  database:

# staging:
#   <<: *default
#   database: kan-go_staging
#   username: kan-go
#   password: <%= ENV['KAN-GO_DATABASE_PASSWORD'] %>
#
# production:
#   <<: *default
#   database: kan-go_production
#   username: kan-go
#   password: db/production.pg
