# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e2ba2cb9f641f713dc619674733be003f48943df92973d959c7c5eaf76dada5ae2424f431e13a1bb9a2c6b47e8d0e7c9f38cd7ff76b99fddc3faff7d120a7e

test:
  secret_key_base: 844d52a49a73521d65056af1cf5f6773c3100c4ca2c9e51ab4033643d8b228160d40c182e4378e76b8a8638c0e94d17bbf4ccca9e39b25e2a5a52469d45b1307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
